apiVersion: v1
kind: Namespace
metadata:
  name: pfsense-logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: pfsense-logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   Off
        storage.metrics on

    [INPUT]
        Name              syslog
        Mode              udp
        Port              5140
        Tag               pfsense
        Parser            syslog
        Buffer_Chunk_Size 2M
        Buffer_Max_Size   5M

    [FILTER]
        Name           record_modifier
        Match          *
        Record         hostname pfsense

    [OUTPUT]
        Host    logs-prod-036.grafana.net
        Port    443
        TLS     on
        tenant_id 1176576
        user     1176576
        password glsa_EKNLCRO362hWRIXhaOkJz2MmhhM4EhXJ_bb911c2a
  parsers.conf: |
    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^(?<time>[^ ]+\s+[^ ]+) (?<log>.*)
        Time_Key    time
        Time_Format %b %d %H:%M:%S
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-udp
  namespace: pfsense-logging
  annotations:
    metallb.universe.tf/allow-shared-ip: fluent-bit-udp  
    metallb.universe.tf/loadBalancerIPs: 10.0.0.120
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: fluent-bit
  ports:
    - name: syslog-udp
      protocol: UDP
      port: 5140
      targetPort: 5140

