apiVersion: v1
kind: Namespace
metadata:
  name: pfsense-logging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: pfsense-logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   Off
        storage.metrics on

    [INPUT]
        Name              syslog
        Mode              udp
        Port              5140
        Tag               pfsense
        Parser            pfsense_syslog
        Buffer_Chunk_Size 2M
        Buffer_Max_Size   5M

    [FILTER]
        Name           record_modifier
        Match          *
        Record         hostname pfsense

    [OUTPUT]
        Name           stackdriver
        Match          *
        Resource       generic_node
        google_service_credentials /fluent-bit/gcp-creds.json
        location       us-east1
        namespace      pfsense
        node_id        pfsense-fw01
  parsers.conf: |
    [PARSER]
        Name        pfsense_syslog
        Format      regex
        Regex       ^<\d+>(?<time>\w{3}\s+\d{1,2}\s+\d{2}:\d{2}:\d{2}) (?<log>.*)
        Time_Key    time
        Time_Format %b %d %H:%M:%S
---
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-gcp-creds
  namespace: pfsense-logging
type: Opaque
data:
  gcp-creds.json: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGZzZW5zZS1sb2dnaW5nLWluZnJhLTU3Y2QiLAogICJwcml2YXRlX2tleV9pZCI6ICIzZTQxOWE0NWVlN2RjOWMxNmEzMTJhNTU5NTQwNmY5YTk5ODcwOGFjIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUNQelFOVm8wUU90TDVqXG42ZFByWHpJK1VWeVQrNEp5YStNL1Vlb3BQbzdzUnJBSVJqOVZqWHYveHpneFg4QTYxeXFVbk5QNHNpYmx4czdRXG5FYml4VjF5dXdzdzlSM2VlRE9zdnZObnpUU1VwekxscUI2a3RFZDU0NHJwUzRsTVVLMGdyTHdqSE1LNWVYeXVtXG43dFVwRkFZK2hsRGlJVUtjL2JzNDZQN0ZpUXRTaEp0YzBzM2ZPMXl2aTVYWkhwajE2NmgzeUJOQWgwd0dXMXluXG5VL1I5a09XQTFNUTFqeldlcys2bW5ycnpoN1pZLzRCZnNJbTBtUU5CbDFETUFQa3RHZkVvWS9oR3R4N3kyTWFuXG5qUDUxMGcvN0RDaHhzTnZjLzdQc3VEcEQwbGVCR1FJMW5vY2xGWGtxWGpMTHZTK3p6SU1NellQazFGYkFtelNlXG5kWXN2RldBREFnTUJBQUVDZ2dFQUllTFNROVp1M2JaSzNUbUhOa0pmRVI5VUhRMGFEc09NcittcUwrRHRoaEVjXG5QejdxZ3NzTjZ0YXp6N0s4RmtHSTU2OVRKaG81SDFGcmY4MkZROGtON3FLNXhVRDNsNWQ4dm1tV3hJWXIyVDlFXG5mQTlsRnRsTW54anloa0NPQ2tVdXd2cFk2N04xaTRpS3ZWSXZpZmdOaHFOWklRaHNiWmsvQ3FpaERNU0FGZ2dPXG5GUWpoVmprc0MwalRkdER0YzFWZEczU2g3djBDd2plUHFJK3hpcEUzdTJWSmJNbVZwdlFLRVVicmZlaUhOcHprXG5wc1VZckwzbzhLQW9rVDZDOENsQ1NRbHhiaHA3M0dyYk93VHlTclpGdFNKYzBVQTc2ZFQ3UlRQVEFnYjZOcnNjXG5kMXdOcGg4N053R2lMOVQzWjRmczRuOVBjMU5peVJ2dmxmbGNrMnVvVlFLQmdRREtQbHZMbFE2eUJDMWJUalprXG5nZENCbXY5cUVFWVR1dERWb3MxZk5jL0J1aXByenlYU1kvZXpDN3dkYmlYVDI0U3kwOGtQM2hrZW12eHU1WWc1XG51T3hqQk9WYXROZW1uZng0WnYxWFJBL3Vpa0VncUF3U29pL1hxNmVQS2NxekpDbXZCckhGVEZBa1NZTzExeTRTXG5QbFlyeDFiTVZZeDhVd0h3WTlCRHJNUExKd0tCZ1FDMkJleUZzdHJ5dUZtRVRsQXhpQ0FWbFptaWtvdmVTZllIXG5SdGU1UVdCZ29HNW9UL05GdXhlMzdxV1JWUElCN3Z4aXY5V2RtS0JPUEF5ZWhzZysrWEVmUlE3dWVJMjliSmczXG5EQTFPZHpyR3IzNGtFTDFicW5rdURGRWpycGJUaVZSc0RISDl1Z1gzVzVhNmJoWm1rL3VHMEc0Vy9SaENsa1ArXG5WZVg2RHdoOXhRS0JnUUNpazZ4aEpHclN5YTdZWmpBdGJYbDZwbW5LRGxqM0JVZFpaVzBvcTI1ZWNsUWxwRGpvXG5QdnBnMFA4Z3ZXbmxPK01aaWt4bjJBZGpaZjJrL0JrZEpiM0kvNmVMMmpJOU8yVTRPTHBSQzJLdlJDNkVuUEpQXG5qRmRmVFJyK1ovOE5NUFhkUUVscHJDWUVkYUJPYmpNWDhVcCtHTmw2bXc2NjVsTjV0aE0yUTh5Rkl3S0JnRkNrXG5ZVHgrbCtnTzZvSG1YRHNGandsaEJQYjByQWpvaFpxRnRVODYrcUwwa05XZ0RpeG5qa09MOUVobDlPNE1YajYxXG50TU1rZW1rT3k1eDBKRVZhSjlidHRvYktYQ2wrOGhUNVB1L3pmTlBIcmovMk5wNWs4VmtJVmU1VUREaGQwRXdxXG5XMXBJenhuZXR2R1RrbE1SM3M3RWl2R2VZZUFtU0t0bWpRUHpJeFR0QW9HQUlLWVJzdWtJZE5BV3c5YU5QeVZWXG5SNk5ick5FY0tDcU5XdWZoYWg0U1ZESDJKUm9MK0JiaU50bVkyMjFPTGR4cFFUenF6UTJBK3lReTFjNjFISSs5XG5UK3FFaytrRmovSEpqYUlQc3hleCtxUWxDMURHbU1UYy9Ub1pQM0RMbkdscUVaZWJ0Y1ZJZk5Kak1tUHNzOS9CXG5PYzc4dHNoSVhjTTYxSEVJRlBrSDFSWT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJwZnNlbnNlLWxvZ3NAcGZzZW5zZS1sb2dnaW5nLWluZnJhLTU3Y2QuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE3MzUwOTQ3OTQ0ODI2NzAxMjc1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9wZnNlbnNlLWxvZ3MlNDBwZnNlbnNlLWxvZ2dpbmctaW5mcmEtNTdjZC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQo=
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: pfsense-logging
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          ports:
            - containerPort: 5140
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: gcp-creds
              mountPath: /fluent-bit/gcp-creds.json
              subPath: gcp-creds.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: fluent-bit-config
        - name: gcp-creds
          secret:
            secretName: fluent-bit-gcp-creds
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-udp
  namespace: pfsense-logging
  annotations:
    metallb.universe.tf/allow-shared-ip: fluent-bit-udp  
    metallb.universe.tf/loadBalancerIPs: 10.0.0.120
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: fluent-bit
  ports:
    - name: syslog-udp
      protocol: UDP
      port: 5140
      targetPort: 5140

